version: 2

models:
  - name: stg_eia_electricity
    columns:
      - name: period
        tests:
          - not_null
      - name: stateid
        tests:
          - not_null
      - name: sector_id
        tests:
          - not_null
          - accepted_values:
              values: ['RES', 'COM', 'IND']
  
  - name: stg_epri_datacenter_load
    columns:
      - name: stateid
        tests:
          - not_null
      - name: year
        tests:
          - not_null
      - name: scenario
        tests:
          - not_null
          - accepted_values:
              values: ['baseline', 'low', 'moderate', 'high', 'higher']
      - name: annual_energy_gwh
        tests:
          - not_null